name: rapid
version: 0.0.1-dev
author: Jean Grizet <jean.grizet@gmail.com>
description: A polygon interference detection library
homepage: https://github.com/Kordam/Rapid.dart
dependencies:
  vector_math:
      git: https://github.com/johnmccutchan/vector_math.git
  browser: any
dev_dependencies:
  unittest: any
  three:
      git: ssh://git@gitlab.kordam.fr:2222/kordam/three.git