name: Rapid.dart
version: 0.0.1-dev
author: Jean Grizet <jean.grizet@gmail.com>
description: A polygon interference detection library
homepage: https://github.com/Kordam/Rapid.dart
dependencies:
  vector_math: '>=1.4.0 <1.5.0'
  browser: any
  test: '>=0.12.0 <0.13.0'